#!/usr/bin/env bash

## Check response status on a list of urls.
##
## Usage: fin kit/check-url <args>

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/${DOCROOT}
fin drush kit:check-url "$@"
#-------------------------- END: Execution --------------------------------
