#!/usr/bin/env bash

## Import/export environment specific configuration for a site
##
## Usage: fin kit/conf <args>

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/${DOCROOT}
fin drush kit:conf "$@"
#-------------------------- END: Execution --------------------------------
