#!/usr/bin/env php
<?php
## Import/export environment specific configuration for a site
##
## Usage: fin kit/conf
#: exec_target = cli

if (empty($argv[1])) {
  unset($_SERVER['argv'][1]);
  unset($argv[1]);
}

$loader = require_once '/var/www/' . $_ENV['DOCROOT'] . '/autoload.php';

use DrupalKit\Docksal\Util\SingleCommandApplication;
use DrupalKit\Docksal\Command\DrupalConfig;

$application = new SingleCommandApplication(new DrupalConfig());
$application->run();
