#!/usr/bin/env bash

## Run drush command in project docroot
##
## Usage: fin kit/drush <command>

#-------------------------- Execution --------------------------------

cd $PROJECT_ROOT/$DOCROOT

# @todo Find uri in yaml and pass through from alias
# @todo maybe convert to php

fin drush $@

#-------------------------- END: Execution --------------------------------
