#!/usr/bin/env bash

## Run eslint against specified files, dirs
##
## Usage: fin kit/eslint <path>

#-------------------------- Sanity Check --------------------------------

if [[ "$1" == "" ]]; then
  echo "Usage: fin kit/eslint <path>"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

EXIT_CODE=0

fin run eslint --quiet $@ || fin util && fin run eslint --quiet $@

EXIT_CODE=$(($EXIT_CODE + $?)) 
exit $EXIT_CODE

#-------------------------- END: Execution --------------------------------
