#!/usr/bin/env bash
#: exec_target = cli

## Run gulp in the theme source directory

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/source
npm run gulp "$@"
#-------------------------- END: Execution --------------------------------
