#!/usr/bin/env bash

# Abort if anything fails
set -e

## Lint and test the projects' custom and source files.

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/${DOCROOT}/
fin kit/gulp test
fin kit/phpcs modules/custom/
fin kit/phpcs themes/custom/
#-------------------------- END: Execution --------------------------------
