#!/usr/bin/env bash
#: exec_target = cli
## Run npm in the theme source directory

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/source
npm "$@"
#-------------------------- END: Execution --------------------------------
