#!/usr/bin/env bash
#: exec_target = cli

# Abort if anything fails
set -e

## Run Code Sniffer (phpcs) against given path
##
## Usage: fin kit/phpcs <path>
##
## Uses Drupal standards.
##
## Includes extensions:	php, module, inc, install, test, profile, theme
## Ignores:		features.*, *.pages*.inc

#-------------------------- Execution --------------------------------
# Wrap the command below to hide output.
output=$(/var/www/vendor/bin/phpcs --config-set installed_paths /var/www/vendor/drupal/coder/coder_sniffer)

/var/www/vendor/bin/phpcs \
  --standard=Drupal -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.pages*.inc,*.yml,.docksal,*.js,*.jpg,*.png,settings*.php,*.txt" \
  "$@"
#-------------------------- END: Execution --------------------------------
