#!/usr/bin/env bash

## Run Code Sniffer (phpcbf) against given path
##
## Usage: fin kit/phpcbf <path>
##
## Uses Drupal standards.
##
## Includes extensions: php, module, inc, install, test, profile, theme
## Ignores:   *.pages*.inc

#-------------------------- Sanity Check --------------------------------

if [[ "$1" == "" ]]; then
  echo "Usage: fin kit/phpcbf <path>"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

fin run kit/phpcbf \
  --standard=Drupal -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.pages*.inc" \
  "$1"

#-------------------------- END: Execution --------------------------------
