#!/usr/bin/env bash

## Run Code Sniffer (phpcs) against given path
##
## Usage: fin kit/phpcs <path>
##
## Uses Drupal standards.
##
## Includes extensions: php, module, inc, install, test, profile, theme
## Ignores: features.*, *.pages*.inc

#-------------------------- Sanity Check --------------------------------

if [[ "$1" == "" ]]; then
  echo "Usage: fin kit/phpcs <path>"
  exit 1
fi

#-------------------------- END: Sanity Check --------------------------------

#-------------------------- Execution --------------------------------

EXIT_CODE=0

fin run phpcs \
  --colors \
  --standard=Drupal -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.pages*.inc,*.yml,.docksal,*.js,*.jpg,*.png,settings*.php,*.txt" \
  "$1"

EXIT_CODE=$(($EXIT_CODE + $?))

fin run phpcs \
  --colors \
  --standard=DrupalPractice -n \
  --extensions="php,module,inc,install,test,profile,theme" \
  --ignore="*.pages*.inc,*.yml,.docksal,*.js,*.jpg,*.png,settings*.php,*.txt" \
  "$1"

EXIT_CODE=$(($EXIT_CODE + $?)) 

exit $EXIT_CODE

#-------------------------- END: Execution --------------------------------
