#!/usr/bin/env bash

## Sync local environment with most recent code, database, and configuration.
##
## Usage: fin kit/conf <args>

#-------------------------- Execution --------------------------------
cd ${PROJECT_ROOT}/${DOCROOT}
fin drush kit:sync "$@"
#-------------------------- END: Execution --------------------------------
